# spring.config.import=optional:file:.env

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

supabase.url=https://${SUPABASE_PROJEKT_ID}.supabase.co
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://${SUPABASE_PROJEKT_ID}.supabase.co/auth/v1/.well-known/jwks.json
supabase.anon.key=${SUPABASE_JWT_SECRET}
logging.level.org.springframework.security=DEBUG

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect